SPL-462 - Create privacy policy
UKGovernmentBEIS/beis-spl-planner pull request #278
Opened 2024-10-28 18:49 UTC by Louis-Solirius

[SPL-462](https://solirius.atlassian.net/browse/SPL-462)

2024-10-29 09:37 UTC, devind-ra reviewed
Looks good to me! Just needs minor edits as there is a separate privacy notice for PT (linked on ticket in the comments) and for ET.

2024-10-29 09:37 UTC, devind-ra commented on app/views/privacy-notice.njk
> +            <p>This privacy notice explains how the Department for Business and Trade (DBT), as a ‘data controller’, processes personal data for the ‘Check if you can get Shared Parental Leave and Pa
Add  ‘Plan your Shared Parental Leave and Pay’ for ‘Check if you can get Shared Parental Leave and Pay’

2024-10-29 09:37 UTC, devind-ra commented on app/views/privacy-notice.njk
> +            <p>Personal data is collected through the ‘Check if you can get Shared Parental Leave and Pay’ service to enable individuals to check their eligibility for Shared Parental Leave and Share
Add  ‘Plan your Shared Parental Leave and Pay’ for ‘Check if you can get Shared Parental Leave and Pay’

2024-10-29 09:37 UTC, devind-ra commented on app/views/privacy-notice.njk
> +            <p>Data entered into the ‘Check if you can get Shared Parental Leave and Pay’ service is not stored in any database. It is only held temporarily to enable you to complete your use of the
Add second paragraph from the document in this section from the PT privacy notice

2024-10-29 10:20 UTC, Louis-Solirius commented on app/views/privacy-notice.njk
> +            <p>This privacy notice explains how the Department for Business and Trade (DBT), as a ‘data controller’, processes personal data for the ‘Check if you can get Shared Parental Leave and Pa
Ah, you've caught me being lazy! I did just steal it from your PR haha

2024-10-29 10:22 UTC, devind-ra commented on app/views/privacy-notice.njk
> +            <p>This privacy notice explains how the Department for Business and Trade (DBT), as a ‘data controller’, processes personal data for the ‘Check if you can get Shared Parental Leave and Pa
haha that makes a lot of sense now, it's all good

2024-11-08 14:28 UTC, lambley requested changes
Changes needed to text - see comments fromm @devind-ra

2024-11-13 15:50 UTC, devind-ra approved these changes

2024-11-13 15:51 UTC, merged