SPL-464 - Update cookie banner
UKGovernmentBEIS/beis-spl-planner pull request #281
Opened 2024-10-31 16:22 UTC by devind-ra

2024-10-31 17:39 UTC, Louis-Solirius commented on app/views/layout.njk
> +        <p>You’ve accepted additional cookies. You can <a class="govuk-link" href="/cookies">change your cookie settings</a> at any time.</p>
I'm not sure this is working, when I click accept or reject nothing comes up, when this looks like it should make something come up

2024-10-31 17:40 UTC, Louis-Solirius commented on app/views/layout.njk
> +        <h1 class="govuk-heading-m">Cookies on {{ service_name }}</h1>
Where is `service_name` defined? (Insanely nit-picky) but can we change the text to be upper case?

2024-10-31 17:47 UTC, devind-ra commented on app/views/layout.njk
> +        <p>You’ve accepted additional cookies. You can <a class="govuk-link" href="/cookies">change your cookie settings</a> at any time.</p>
ah yes with that I was trying to implement a confirmation message after you reload the website but I could't implement it. Will remove it for now

2024-10-31 17:52 UTC, devind-ra commented on app/views/layout.njk
> +        <h1 class="govuk-heading-m">Cookies on {{ service_name }}</h1>
I think it was from the file but I'm not too sure - https://github.com/UKGovernmentBEIS/beis-spl-planner/blob/master/server.js

2024-10-31 17:56 UTC, Louis-Solirius commented on app/views/layout.njk
> +        <h1 class="govuk-heading-m">Cookies on {{ service_name }}</h1>
it's in app/constants.js. @lambley can we change `SERVICE_NAME: 'Plan shared parental leave and pay'` to `SERVICE_NAME: 'Plan Shared Parental Leave and Pay'`?

2024-11-01 09:00 UTC, lambley commented on app/views/layout.njk
> +        <h1 class="govuk-heading-m">Cookies on {{ service_name }}</h1>
I've changed this SERVICE_NAME to title case

2024-11-01 09:01 UTC, lambley requested changes
Padding issue on the cookie banner needs to be fixed

2024-11-05 16:17 UTC, lambley approved these changes

2024-11-05 16:53 UTC, merged